**Auteur(s)** : Cheikhou Akhmed KANE

**Description** : Mise en place `reglesDeDecisions_fertilisation.csv`

# Mise en place `reglesDeDecisions_fertilisation.csv`

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
base_dir = Path.cwd().parent.resolve()

# Fichier en entrée
input_regles_path = base_dir / "data" / "ITK" / "csv" / "raw" / "reglesDeDecisions_fertilisation.csv"

# Fichier en sortie
output_ferti_path = base_dir / "includes_sassemeV1" / "modeleAgricole" / "culture" / "reglesDeDecisions_fertilisation.csv"

# Liste de nos 6 ITK cibles
itk_sasseme = [
    'arachide_precMil',
    'arachide_precJachere',
    'jachere_precMil',
    'jachere_precArachide',
    'mil_precArachide',
    'mil_precMil'
]

In [3]:
try:
    df_source = pd.read_csv(input_regles_path, sep=';')
    print("✅ Fichier source des règles de fertilisation chargé avec succès.")
except Exception as e:
    print(f"🚨 ERREUR lors du chargement du fichier : {e}")

✅ Fichier source des règles de fertilisation chargé avec succès.

In [4]:
# On garde les 2 premières colonnes de base et on ajoute nos 6 ITK
colonnes_base = df_source.columns[:2].tolist()
df_sasseme_ferti = df_source[colonnes_base].copy()

for itk in itk_sasseme:
    df_sasseme_ferti[itk] = "NA" # On initialise tout à NA par défaut
print("✅ Structure du nouveau DataFrame créée.")

✅ Structure du nouveau DataFrame créée.

In [5]:
# Dictionnaire des paramètres fixes à appliquer
parametres_ferti = {
    'FERTIALT_NOM_ALTERNATIVE': 'fertilisation minerale',
    'FERTIALT_ORDRE_ALTERNATIVE': 1,
    'FERTIALT_ORDRE_APPORT': 1,
    'FERTIALT_NOM_PRODUIT': 'NPK',
    'FERTIALT_DOSE': 300,
    'FERTIALT_DOSE_P': 20,
    'FERTIALT_DOSE_K': 10,
    'FERTIALT_PROF_WSOL': 0,
    'FERTIALT_AGRIW': 'oui',
    'FERTIALT_OUTIL': 0,
    'FERTIALT_TPS_TRAVAIL': 0.0625, # 2 jours/ha converti en ha/h
    'FERTIALT_N_PASSAGES': 1,
    'FERTIALT_OT_SIMULTANEE': 'NA',
    'FERTIALT_N_SOUS_PERIODES': 1,
    'FERTIALT_DEBUT': 166, # 15 Juin
    'FERTIALT_FIN': 242   # 30 Août
}

In [6]:
# Appliquer les valeurs à nos 6 colonnes d'ITK
for parametre, valeur in parametres_ferti.items():
    df_sasseme_ferti.loc[df_sasseme_ferti['FERTIALT_NOM_ITK'] == parametre, itk_sasseme] = valeur
print("✅ Paramètres de fertilisation spécifiques appliqués.")

✅ Paramètres de fertilisation spécifiques appliqués.

In [7]:
display(df_sasseme_ferti)

,FERTIALT_NOM_ITK,Unnamed: 1,arachide_precMil,arachide_precJachere,jachere_precMil,jachere_precArachide,mil_precArachide,mil_precMil
0,FERTIALT_NOM_ALTERNATIVE,NaN,fertilisation minerale,fertilisation minerale,fertilisation minerale,fertilisation minerale,fertilisation minerale,fertilisation minerale
1,FERTIALT_ORDRE_ALTERNATIVE,NaN,1,1,1,1,1,1
2,FERTIALT_ORDRE_APPORT,NaN,1,1,1,1,1,1
3,FERTIALT_NOM_PRODUIT,NaN,NPK,NPK,NPK,NPK,NPK,NPK
4,FERTIALT_DOSE,DOSE,300,300,300,300,300,300
5,FERTIALT_DOSE_P,DOSE_P,20,20,20,20,20,20
6,FERTIALT_DOSE_K,DOSE_K,10,10,10,10,10,10
7,FERTIALT_PROF_WSOL,EFFET_RUs,0,0,0,0,0,0
8,FERTIALT_AGRIW,NaN,oui,oui,oui,oui,oui,oui
9,FERTIALT_OUTIL,NaN,0,0,0,0,0,0
10,FERTIALT_TPS_TRAVAIL,TEMPS,0.0625,0.0625,0.0625,0.0625,0.0625,0.0625
11,FERTIALT_N_PASSAGES,NaN,1,1,1,1,1,1
12,FERTIALT_OT_SIMULTANEE,NaN,NA,NA,NA,NA,NA,NA
13,FERTIALT_N_SOUS_PERIODES,NB_SOUS_PERIODES,1,1,1,1,1,1
14,FERTIALT_DEBUT,DEBUT,166,166,166,166,166,166
15,FERTIALT_FIN,FIN,242,242,242,242,242,242
16,FERTIALT_HUM_MAX_SOL,HUMIDITE_SOL_MAX,NA,NA,NA,NA,NA,NA
17,FERTIALT_N_J_CUMUL_PLUIE,JOURS_PLUIE,NA,NA,NA,NA,NA,NA
18,FERTIALT_CUMUL_PLUIE,HAUTEURS_PLUIE_MAX,NA,NA,NA,NA,NA,NA
19,FERTIALT_N_J_CUMUL_PLUIE_EVA,JOURS_P-ETP,NA,NA,NA,NA,NA,NA
20,FERTIALT_CUMUL_PLUIE_EVA,P-ETP_MAX,NA,NA,NA,NA,NA,NA
21,FERTIALT_N_J_CUMUL_TEMP_MIN,JOURS_TMIN,NA,NA,NA,NA,NA,NA
22,FERTIALT_TEMP_MIN,TMIN_MIN,NA,NA,NA,NA,NA,NA
23,FERTIALT_N_J_CUMUL_TEMP_MAX,NaN,NA,NA,NA,NA,NA,NA
24,FERTIALT_TEMP_MAX,NaN,NA,NA,NA,NA,NA,NA
25,FERTIALT_N_J_CUMUL_TEMP_MAX_INF,NaN,NA,NA,NA,NA,NA,NA
26,FERTIALT_TEMP_MAX_INF,NaN,NA,NA,NA,NA,NA,NA
27,FERTIALT_SEUIL_VEGE,ECHV_MIN,NA,NA,NA,NA,NA,NA
28,FERTIALT_SEUIL_VEGE_PRE,ECHV_DEBUT,NA,NA,NA,NA,NA,NA
29,FERTIALT_SEUIL_VEGE_POST,ECHV_FIN,NA,NA,NA,NA,NA,NA
30,FERTIALT_N_J_CUMUL_PLUIE_PREVUE,JOURS_PLUIE_PREVUES,NA,NA,NA,NA,NA,NA
31,FERTIALT_CUMUL_PLUIE_PREVUE,HAUTEURS_PLUIE_PREVUES,NA,NA,NA,NA,NA,NA
32,FERTIALT_N_J_CUMUL_HYGROMETRIE_MIN,NaN,NA,NA,NA,NA,NA,NA
33,FERTIALT_HYGROMETRIE_MIN,NaN,NA,NA,NA,NA,NA,NA
34,FERTIALT_HAUTEUR_AU_MOINS_CUMUL_PLUIES_PREVUES,HAUTEUR_AU_PLUS_CUMUL_PLUIES_PREVUES,NA,NA,NA,NA,NA,NA
35,FERTIALT_NJ_AU_MOINS_CUMUL_PLUIES_PREVUES,NJ_AU_PLUS_CUMUL_PLUIES_PREVUES,NA,NA,NA,NA,NA,NA

In [8]:
output_ferti_path.parent.mkdir(parents=True, exist_ok=True)
df_sasseme_ferti.to_csv(output_ferti_path, sep=';', index=False)
print(f"\n✅ Fichier 'reglesDeDecisions_fertilisation.csv' sauvegardé dans :\n   {output_ferti_path}")

✅ Fichier 'reglesDeDecisions_fertilisation.csv' sauvegardé dans :
   C:\Users\Cheikhou\Desktop\Ferlo_Sine\maelia-data-diohine-v1\includes_sassemeV1\modeleAgricole\culture\reglesDeDecisions_fertilisation.csv

In [9]:
print("\nAperçu du fichier final :")
display(df_sasseme_ferti.head(15))

Aperçu du fichier final :

,FERTIALT_NOM_ITK,Unnamed: 1,arachide_precMil,arachide_precJachere,jachere_precMil,jachere_precArachide,mil_precArachide,mil_precMil
0,FERTIALT_NOM_ALTERNATIVE,NaN,fertilisation minerale,fertilisation minerale,fertilisation minerale,fertilisation minerale,fertilisation minerale,fertilisation minerale
1,FERTIALT_ORDRE_ALTERNATIVE,NaN,1,1,1,1,1,1
2,FERTIALT_ORDRE_APPORT,NaN,1,1,1,1,1,1
3,FERTIALT_NOM_PRODUIT,NaN,NPK,NPK,NPK,NPK,NPK,NPK
4,FERTIALT_DOSE,DOSE,300,300,300,300,300,300
5,FERTIALT_DOSE_P,DOSE_P,20,20,20,20,20,20
6,FERTIALT_DOSE_K,DOSE_K,10,10,10,10,10,10
7,FERTIALT_PROF_WSOL,EFFET_RUs,0,0,0,0,0,0
8,FERTIALT_AGRIW,NaN,oui,oui,oui,oui,oui,oui
9,FERTIALT_OUTIL,NaN,0,0,0,0,0,0
10,FERTIALT_TPS_TRAVAIL,TEMPS,0.0625,0.0625,0.0625,0.0625,0.0625,0.0625
11,FERTIALT_N_PASSAGES,NaN,1,1,1,1,1,1
12,FERTIALT_OT_SIMULTANEE,NaN,NA,NA,NA,NA,NA,NA
13,FERTIALT_N_SOUS_PERIODES,NB_SOUS_PERIODES,1,1,1,1,1,1
14,FERTIALT_DEBUT,DEBUT,166,166,166,166,166,166